<a href="https://colab.research.google.com/github/name234532/colab-test/blob/main/colab_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('welcome')

welcome


In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
# url='/content/drive/MyDrive/Colab Notebooks/csv-folder/경찰청_범죄자 생활정도, 혼인관계 및 부모관계_20151231.csv'

In [ ]:
import pandas as pd 

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/csv-folder/netflix_titles.csv')

In [ ]:
df.head()

show_id  ...                                        description
0      s1  ...  In a future where the elite inhabit an island ...
1      s2  ...  After a devastating earthquake hits Mexico Cit...
2      s3  ...  When an army recruit is found dead, his fellow...
3      s4  ...  In a postapocalyptic world, rag-doll robots hi...
4      s5  ...  A brilliant group of students become card-coun...

[5 rows x 12 columns]

In [ ]:
import numpy as np

In [ ]:
df2= pd.DataFrame({
    'name':['hong','park'],
    'age':[10,20]
})

In [ ]:
df2

name  age
0  hong   10
1  park   20

In [ ]:
df2.index

RangeIndex(start=0, stop=2, step=1)

In [ ]:
df2.values

array([['hong', 10],
       ['park', 20]], dtype=object)

In [ ]:
df2.name

0    hong
1    park
Name: name, dtype: object

In [ ]:
df2['name']

0    hong
1    park
Name: name, dtype: object

In [ ]:
df2.name.index

RangeIndex(start=0, stop=2, step=1)

In [ ]:
df2.name.values

array(['hong', 'park'], dtype=object)

In [ ]:
df2.name.values.tolist()

['hong', 'park']

In [ ]:
list(df2.name.values)

['hong', 'park']

In [ ]:
df3= pd.DataFrame(data=[['hong',10],['park',20]], columns=['name', 'age'])

In [ ]:
df3

name  age
0  hong   10
1  park   20

In [ ]:
df3.dtypes

name    object
age      int64
dtype: object

In [ ]:
df3['age'].astype(float)

0    10.0
1    20.0
Name: age, dtype: float64

In [ ]:
df3

name  age
0  hong   10
1  park   20

In [ ]:
df3.dtypes

name    object
age      int64
dtype: object

In [ ]:
df3['age']=df3['age'].astype(float)

In [ ]:
df3

name   age
0  hong  10.0
1  park  20.0

In [ ]:
df3['age']=df3['age'].astype(int)

In [ ]:
df3

name  age
0  hong   10
1  park   20

In [ ]:
df3.describe()

age
count   2.000000
mean   15.000000
std     7.071068
min    10.000000
25%    12.500000
50%    15.000000
75%    17.500000
max    20.000000

In [ ]:
type(df3['name'])

pandas.core.series.Series

In [ ]:
df3['name']

0    hong
1    park
Name: name, dtype: object

In [ ]:
df3['name'].index

RangeIndex(start=0, stop=2, step=1)

In [ ]:
df3['name'].values

array(['hong', 'park'], dtype=object)

In [ ]:
type(df3['name'].values)

numpy.ndarray

In [ ]:
mask =np.zeros((3,4))
mask

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr2=np.array([
    [1,2,3], [4,5,6]
],dtype=np.float64)
arr2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
arr3=np.array([
    [7,8,9], [10,11,12]
],dtype=np.float64)
arr3

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [ ]:
arr2+arr3

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [ ]:
arr2*arr3

array([[ 7., 16., 27.],
       [40., 55., 72.]])