<a href="https://colab.research.google.com/github/name234532/colab-test/blob/main/colab_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('welcome')

welcome


In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
# url='/content/drive/MyDrive/Colab Notebooks/csv-folder/경찰청_범죄자 생활정도, 혼인관계 및 부모관계_20151231.csv'

In [ ]:
import pandas as pd 

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/csv-folder/netflix_titles.csv')

In [ ]:
df.head()

show_id  ...                                        description
0      s1  ...  In a future where the elite inhabit an island ...
1      s2  ...  After a devastating earthquake hits Mexico Cit...
2      s3  ...  When an army recruit is found dead, his fellow...
3      s4  ...  In a postapocalyptic world, rag-doll robots hi...
4      s5  ...  A brilliant group of students become card-coun...

[5 rows x 12 columns]

In [ ]:
import numpy as np

In [ ]:
df2= pd.DataFrame({
    'name':['hong','park'],
    'age':[10,20]
})

In [ ]:
df2

name  age
0  hong   10
1  park   20

In [ ]:
df2.index

RangeIndex(start=0, stop=2, step=1)

In [ ]:
df2.values

array([['hong', 10],
       ['park', 20]], dtype=object)

In [ ]:
df2.name

0    hong
1    park
Name: name, dtype: object

In [ ]:
df2['name']

0    hong
1    park
Name: name, dtype: object

In [ ]:
df2.name.index

RangeIndex(start=0, stop=2, step=1)

In [ ]:
df2.name.values

array(['hong', 'park'], dtype=object)

In [ ]:
df2.name.values.tolist()

['hong', 'park']

In [ ]:
list(df2.name.values)

['hong', 'park']

In [ ]:
df3= pd.DataFrame(data=[['hong',10],['park',20]], columns=['name', 'age'])

In [ ]:
df3

name  age
0  hong   10
1  park   20

In [ ]:
df3.dtypes

name    object
age      int64
dtype: object

In [ ]:
df3['age'].astype(float)

0    10.0
1    20.0
Name: age, dtype: float64

In [ ]:
df3

name  age
0  hong   10
1  park   20

In [ ]:
df3.dtypes

name    object
age      int64
dtype: object

In [ ]:
df3['age']=df3['age'].astype(float)

In [ ]:
df3

name   age
0  hong  10.0
1  park  20.0

In [ ]:
df3['age']=df3['age'].astype(int)

In [ ]:
df3

name  age
0  hong   10
1  park   20

In [ ]:
df3.describe()

age
count   2.000000
mean   15.000000
std     7.071068
min    10.000000
25%    12.500000
50%    15.000000
75%    17.500000
max    20.000000

In [ ]:
type(df3['name'])

pandas.core.series.Series

In [ ]:
df3['name']

0    hong
1    park
Name: name, dtype: object

In [ ]:
df3['name'].index

RangeIndex(start=0, stop=2, step=1)

In [ ]:
df3['name'].values

array(['hong', 'park'], dtype=object)

In [ ]:
type(df3['name'].values)

numpy.ndarray

In [ ]:
mask =np.zeros((3,4))
mask

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr2=np.array([
    [1,2,3], [4,5,6]
],dtype=np.float64)
arr2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
arr3=np.array([
    [7,8,9], [10,11,12]
],dtype=np.float64)
arr3

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [ ]:
arr2+arr3

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [ ]:
arr2*arr3

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [71]:
dates = pd.date_range('20200625',periods = 6)
dates

DatetimeIndex(['2020-06-25', '2020-06-26', '2020-06-27', '2020-06-28',
               '2020-06-29', '2020-06-30'],
              dtype='datetime64[ns]', freq='D')

In [72]:
df= pd.DataFrame(np.random.randn(6,4), index = dates, columns=['A','B','C','D'])
df

A         B         C         D
2020-06-25  0.452746 -0.142182 -0.480475 -0.212833
2020-06-26  2.184662 -0.961741  1.020727 -1.465349
2020-06-27  0.356916 -1.335446  0.467307 -0.812403
2020-06-28 -2.123580  0.297101  0.249363  2.548762
2020-06-29  0.100719  1.607531 -0.757400  0.450292
2020-06-30  1.412583  0.835042  1.075719 -0.995179

In [74]:
type(df)

pandas.core.frame.DataFrame

In [79]:
df['A']

2020-06-25    0.452746
2020-06-26    2.184662
2020-06-27    0.356916
2020-06-28   -2.123580
2020-06-29    0.100719
2020-06-30    1.412583
Freq: D, Name: A, dtype: float64

In [80]:
df[0:3]

A         B         C         D
2020-06-25  0.452746 -0.142182 -0.480475 -0.212833
2020-06-26  2.184662 -0.961741  1.020727 -1.465349
2020-06-27  0.356916 -1.335446  0.467307 -0.812403

In [85]:
df[2:3]

A         B         C         D
2020-06-27  0.356916 -1.335446  0.467307 -0.812403

In [86]:
df[2:4]  #2,4 rows 추출

A         B         C         D
2020-06-27  0.356916 -1.335446  0.467307 -0.812403
2020-06-28 -2.123580  0.297101  0.249363  2.548762

In [87]:
df[1:3] #1,2 rows 추출!

A         B         C         D
2020-06-26  2.184662 -0.961741  1.020727 -1.465349
2020-06-27  0.356916 -1.335446  0.467307 -0.812403

In [89]:
df.loc['2020-06-25']

A    0.452746
B   -0.142182
C   -0.480475
D   -0.212833
Name: 2020-06-25 00:00:00, dtype: float64

In [90]:
type(df.loc['2020-06-25'])

pandas.core.series.Series

In [91]:
df.iloc[0]

A    0.452746
B   -0.142182
C   -0.480475
D   -0.212833
Name: 2020-06-25 00:00:00, dtype: float64

In [93]:
df.iloc[0:2]

A         B         C         D
2020-06-25  0.452746 -0.142182 -0.480475 -0.212833
2020-06-26  2.184662 -0.961741  1.020727 -1.465349

In [94]:
df.loc['2020-06-25']

A    0.452746
B   -0.142182
C   -0.480475
D   -0.212833
Name: 2020-06-25 00:00:00, dtype: float64

In [95]:
df.iloc[[0,2]]

A         B         C         D
2020-06-25  0.452746 -0.142182 -0.480475 -0.212833
2020-06-27  0.356916 -1.335446  0.467307 -0.812403

In [96]:
df.iloc[1:3,0] #[row,column]

2020-06-26    2.184662
2020-06-27    0.356916
Freq: D, Name: A, dtype: float64

In [98]:
df.iloc[:,0:2]

A         B
2020-06-25  0.452746 -0.142182
2020-06-26  2.184662 -0.961741
2020-06-27  0.356916 -1.335446
2020-06-28 -2.123580  0.297101
2020-06-29  0.100719  1.607531
2020-06-30  1.412583  0.835042

In [99]:
df.iloc[1:3,0:2]

A         B
2020-06-26  2.184662 -0.961741
2020-06-27  0.356916 -1.335446

In [106]:
df.loc['2020-06-25':'2020-06-29',['A','C']]

A         C
2020-06-25  0.452746 -0.480475
2020-06-26  2.184662  1.020727
2020-06-27  0.356916  0.467307
2020-06-28 -2.123580  0.249363
2020-06-29  0.100719 -0.757400

In [109]:
df.iloc[1:2,[0,2]]=100
df

A         B           C         D
2020-06-25    0.452746 -0.142182   -0.480475 -0.212833
2020-06-26  100.000000 -0.961741  100.000000 -1.465349
2020-06-27    0.356916 -1.335446    0.467307 -0.812403
2020-06-28   -2.123580  0.297101    0.249363  2.548762
2020-06-29    0.100719  1.607531   -0.757400  0.450292
2020-06-30    1.412583  0.835042    1.075719 -0.995179

In [120]:
df.loc['2020-07-01']=[100,200,300,400]
df.iloc[1,0]=1
df

A           B           C           D
2020-06-25 00:00:00  100.000000    1.000000   -0.480475   -0.212833
2020-06-26 00:00:00    1.000000   -0.961741  100.000000   -1.465349
2020-06-27 00:00:00    0.356916  200.000000    0.467307   -0.812403
2020-06-28 00:00:00   -2.123580    0.297101    0.249363  300.000000
2020-06-29 00:00:00    0.100719    1.607531   -0.757400    0.450292
2020-06-30 00:00:00    1.412583  400.000000    1.075719   -0.995179
2020-07-01           100.000000  200.000000  300.000000  400.000000

In [121]:
df.iloc[0,0]=100
df.iloc[[2,5],1]=[200,400]
df.D[3]=300
df

A           B           C           D
2020-06-25 00:00:00  100.000000    1.000000   -0.480475   -0.212833
2020-06-26 00:00:00    1.000000   -0.961741  100.000000   -1.465349
2020-06-27 00:00:00    0.356916  200.000000    0.467307   -0.812403
2020-06-28 00:00:00   -2.123580    0.297101    0.249363  300.000000
2020-06-29 00:00:00    0.100719    1.607531   -0.757400    0.450292
2020-06-30 00:00:00    1.412583  400.000000    1.075719   -0.995179
2020-07-01           100.000000  200.000000  300.000000  400.000000